### ISSUE TITLE
`GET /profiles/{id}`

### ISSUE THREAD

**Issue by claustra01** [claustra01/hackz-tsumaguro-backend#8]
{id}のユーザーのprofileを取得する

**Comment by pei232C** [comment]
bodyなし

**Comment by pei232C** [comment]
{
"id": "ea34bbbb-55b1-482a-b706-0669f5863731",
"userId": "2c3626b6-b153-4d4e-888e-875c6454bdc2",
"name": "pei",
"misc": "",
"createdAt": "2023-05-21T02:19:58.464Z",
"updatedAt": "2023-05-21T02:19:58.464Z"
}
